### ISSUE TITLE
What should be the name for a Next.js alternative?

### ISSUE THREAD

**Issue by egoist** [egoist/ideas#1]
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Saber)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Saber/vote)
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Aimer)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Aimer/vote)
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Miku)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Miku/vote)
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Mordred)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Mordred/vote)
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Darling)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Darling/vote)
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Harmonie)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Harmonie/vote)
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Pocky)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Pocky/vote)
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Aho)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Aho/vote)
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Chelly)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Chelly/vote)
[![](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Harem)](https://api.gh-polls.com/poll/01CDMFXK1H7QVT7B54JMBH8SKK/Harem/vote)

Or your suggestions?

**Comment by egoist** [comment]
Remix might be a good idea too if I can get the package name 😅

**Comment by gustojs** [comment]
Darling ftw

**Comment by egoist** [comment]
I think I might go for `remix` since I just got the org name on npm https://www.npmjs.com/org/remix 😅 We can publish it as `@remix/cli` then

**Comment by pablopunk** [comment]
@egoist `remix` sounds good! What would be different from next.js?

**Comment by gluons** [comment]
Ops! Unreadable in [GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark). 😅

![screenshot-2018-5-16 what should be the name for a next js alternative issue 1 egoist ideas](https://user-images.githubusercontent.com/4688092/40127512-bc6598e4-5959-11e8-8399-1e22f830ea7b.png)

[Aimer already exist?](https://github.com/egoist/aimer)

`remix` sounds good. I like it.

**Comment by IniZio** [comment]
saber has high votes, but its taken already :thinking:

**Comment by egoist** [comment]
@IniZio the owner of saber has transferred it to me 😄

**Comment by miaoyuxinbaby** [comment]
shino

**Comment by egoist** [comment]
LOL I eventually created a Nuxt.js alternative instead of Next.js.. https://github.com/egoist/saber.js
