### ISSUE TITLE
Git Client for Mac, Linux and Windows

### ISSUE THREAD

**Issue by daltondiaz** [egoist/ideas#4]
## Problem
My SO is linux and most of time I use git in command line or when happens conflicts I use VSCode together of git lens.

## Solution 
I believe we can build a git client in Electron or other framework to meet this demand.

## Benchmarks
[Git Kraken](https://www.gitkraken.com/)
[SourceTree](https://www.sourcetreeapp.com/)

**Comment by egoist** [comment]
And https://www.sublimemerge.com NOT free though

I'm on macOS so [gitup](https://gitup.co) is good enough for me and it's open source.

Why do you want a new one instead of using existing solution like Git Kraken?

**Comment by daltondiaz** [comment]
Because Kraken is pay for commercial use. Its a awesome tool if you working in a open source project.

Nice too GitUp but only for Mac  :cry:

In alternative I'm using the version control of [VSCode](https://code.visualstudio.com/docs/editor/versioncontrol) but I'm stuck on IDE.

**Comment by mittalyashu** [comment]
Hey guys,

Looking for an open source tool for Git works cross-platform, try using **[Thermal](https://thermal.netlify.com/)**.

> Thermal is open-source desktop application allows you to manage all Git repository at one place by providing you a simple to use graphic user interface with built-in features commits, history, repository settings and more.

![image](https://user-images.githubusercontent.com/29014463/56759818-7ae4c580-67b7-11e9-8b63-25e0495f4aa5.png)

Download for **[Windows & Linux](https://thermal.netlify.com/download/)** _(Mac coming soon)_.

**Comment by daltondiaz** [comment]
> Hey guys,
> 
> Looking for an open source tool for Git works cross-platform, try using **[Thermal](https://thermal.netlify.com/)**.
> 
> > Thermal is open-source desktop application allows you to manage all Git repository at one place by providing you a simple to use graphic user interface with built-in features commits, history, repository settings and more.
> 
> ![image](https://user-images.githubusercontent.com/29014463/56759818-7ae4c580-67b7-11e9-8b63-25e0495f4aa5.png)
> 
> Download for **[Windows & Linux](https://thermal.netlify.com/download/)** _(Mac coming soon)_.

Wow, good tool, I get to use thermal today.

Bring Thermal to github =D 

@egoist for me this issue can be closed!!

**Comment by mittalyashu** [comment]
Glad you like Thermal so much @daltondiaz.

BTW, Which operating system do you use?

**Comment by daltondiaz** [comment]
I'm using Ubuntu 18.04.2 LTS  (Bionic Beaver)

**Comment by mittalyashu** [comment]
Great, you can download the appropriate package for Ubuntu from [releases](https://github.com/gitthermal/thermal/releases/tag/v0.0.1).
